-- ============================================================
-- SPD Biotech — seed the public.products table (42 products)
-- Generated for the new two-level category structure.
--
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--
-- Safe to run more than once: rows are matched on id and updated
-- in place, so re-running refreshes the content without creating
-- duplicates. It does NOT delete products that are already there.
--
-- Images are served as static files from public/products/, so the
-- matching .jpg files must be deployed with the site.
-- ============================================================

insert into public.products
  (id, name, name_en, brand, category, tone, icon, image, tagline, description, specs, sort_order)
values
  ('steelco-vs-steam-lab-sterilizer', 'เครื่องนึ่งฆ่าเชื้อด้วยไอน้ำสำหรับห้องปฏิบัติการ VS Series', 'VS Series Steam Lab Sterilizer', 'SteelcoBelimed', 'Autoclave / Steam Sterilizer', 'device', '♨️', '/products/autoclave-steam-sterilizer.jpg', 'Steam lab sterilizer', 'เครื่องนึ่งฆ่าเชื้อด้วยไอน้ำแบบตั้งพื้นสำหรับห้องปฏิบัติการและงานผลิต ห้องนึ่งสแตนเลสพร้อมชั้นวางถอดได้ รองรับการฆ่าเชื้อขวดอาหารเลี้ยงเชื้อ ขวดแก้ว เครื่องแก้ว และอุปกรณ์ที่ทนความร้อน ควบคุมรอบการทำงานผ่านหน้าจอสัมผัสสี พร้อมเครื่องพิมพ์รายงานในตัวสำหรับเก็บหลักฐานแต่ละรอบตามข้อกำหนด GMP มีเกจแสดงความดันและปุ่มหยุดฉุกเฉินที่หน้าเครื่อง

Floor-standing steam sterilizer for laboratory and production use. Stainless chamber with removable shelves handles media bottles, glassware and heat-stable equipment. Colour touchscreen cycle control with a built-in printer for per-cycle records under GMP; pressure gauges and an emergency stop on the front panel.', '[{"label": "ประเภท / Type", "value": "เครื่องนึ่งฆ่าเชื้อด้วยไอน้ำสำหรับห้องปฏิบัติการ (Steam lab sterilizer)"}, {"label": "รุ่นในภาพ / Model shown", "value": "VS 262639 L"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสสี พร้อมเครื่องพิมพ์รายงานในตัว"}, {"label": "ห้องนึ่ง / Chamber", "value": "สแตนเลส พร้อมชั้นวางถอดได้"}, {"label": "ความปลอดภัย / Safety", "value": "เกจแสดงความดัน และปุ่มหยุดฉุกเฉินหน้าเครื่อง"}, {"label": "แบรนด์ / Brand", "value": "SteelcoBelimed (Miele Group Member)"}]'::jsonb, 10),
  ('belimed-pst2-steam-sterilizer', 'เครื่องนึ่งฆ่าเชื้อด้วยไอน้ำอิ่มตัว cGMP รุ่น PST.2 Series', 'PST.2 Series cGMP Saturated Steam Sterilizer', 'SteelcoBelimed', 'Autoclave / Steam Sterilizer', 'device', '♨️', '/products/sterilizer-pst2.jpg', 'Modular cGMP steam sterilizer', 'เครื่องนึ่งฆ่าเชื้อด้วยไอน้ำอิ่มตัวระดับ cGMP สำหรับสายการผลิตยาและชีววัตถุ มีให้เลือก 19 ขนาดห้องฆ่าเชื้อ ตั้งแต่ 366 ถึง 3,553 ลิตร ประตูแบบเลื่อน เลือกได้ทั้งประตูเดี่ยวและประตูคู่สำหรับติดตั้งแบบ pass-through ระหว่างพื้นที่สะอาดต่างระดับ ออกแบบเป็นโมดูลจึงใช้พื้นที่ติดตั้งน้อยกว่าเครื่องขนาดเดียวกัน ควบคุมรอบการฆ่าเชื้อผ่านหน้าจอสัมผัสขนาดใหญ่ที่หน้าเครื่อง

cGMP saturated steam sterilizer for pharmaceutical and biologics production. 19 chamber sizes from 366 to 3,553 litres, with sliding doors available single or double for pass-through installation between classified areas. A modular design keeps the footprint very compact for its capacity; cycles are run from the large front touchscreen.', '[{"label": "รุ่นย่อย / Models", "value": "19 ขนาดห้องฆ่าเชื้อ"}, {"label": "ปริมาตรห้องฆ่าเชื้อ / Chamber volume", "value": "366 – 3,553 ลิตร (13 – 125.5 ft³)"}, {"label": "ประตู / Door type", "value": "Sliding — เลือกได้ทั้งประตูเดี่ยวและประตูคู่"}, {"label": "การจัดวาง / Layout", "value": "ออกแบบเป็นโมดูล ใช้พื้นที่ติดตั้งน้อย"}, {"label": "กลุ่มสินค้า / Range", "value": "cGMP Saturated Steam Sterilizers"}, {"label": "แบรนด์ / Brand", "value": "SteelcoBelimed (Miele Group Member)"}]'::jsonb, 20),
  ('steelco-lab-1500-glassware-washer', 'เครื่องล้างเครื่องแก้วอัตโนมัติ LAB 1500', 'LAB 1500 Glassware Washer', 'SteelcoBelimed', 'Washer', 'device', '🧼', '/products/washer-glassware.jpg', 'Automated glassware washer', 'เครื่องล้างเครื่องแก้วอัตโนมัติแบบตั้งพื้น ประตูกระจกบานเลื่อนขึ้น มองเห็นรอบการล้างได้ตลอดเวลา ภายในรองรับแร็คหลายชั้นพร้อมหัวฉีดสอดเข้าในขวดและเครื่องแก้วคอแคบ ล้างได้ทั้งขวดสื่อเลี้ยงเชื้อ ขวดวัดปริมาตร บีกเกอร์ และอุปกรณ์ห้องปฏิบัติการ ควบคุมรอบการล้างผ่านหน้าจอสัมผัส พร้อมเครื่องพิมพ์รายงานในตัวสำหรับเก็บหลักฐานแต่ละรอบ ช่องเก็บถังสารเคมีอยู่ด้านล่างตัวเครื่อง

Floor-standing automated glassware washer with a vertical-lift glass door for full cycle visibility. Multi-level racks with injection spindles clean media bottles, volumetric flasks, beakers and narrow-neck labware. Touchscreen cycle control with a built-in printer for per-cycle records; detergent containers housed in the lower compartment.', '[{"label": "ประเภท / Type", "value": "เครื่องล้างเครื่องแก้วอัตโนมัติสำหรับห้องปฏิบัติการ"}, {"label": "รุ่นในภาพ / Model shown", "value": "LAB 1500 Glassware Washer"}, {"label": "ประตู / Door", "value": "กระจกบานเลื่อนขึ้น มองเห็นรอบการล้าง"}, {"label": "ระบบล้าง / Washing", "value": "แร็คหลายชั้น พร้อมหัวฉีดสอดสำหรับเครื่องแก้วคอแคบ"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัส พร้อมเครื่องพิมพ์รายงานในตัว"}, {"label": "แบรนด์ / Brand", "value": "SteelcoBelimed (Miele Group Member)"}]'::jsonb, 30),
  ('belimed-ph-810-washer', 'เครื่องล้างชิ้นส่วนและเครื่องแก้ว cGMP รุ่น PH 810', 'PH 810 cGMP Parts & Glassware Washer', 'SteelcoBelimed', 'Washer', 'device', '🧼', '/products/washer-ph810.jpg', 'Fast-to-market cGMP washer', 'เครื่องล้างชิ้นส่วนและเครื่องแก้วระดับ cGMP จากกลุ่ม Fast-to-market Cleaning Systems ห้องล้างขนาด 306 ลิตร (11 ft³) ประตูแบบเลื่อนลง เลือกได้ทั้งประตูเดี่ยวและประตูคู่สำหรับติดตั้งแบบ pass-through ระหว่างพื้นที่สะอาดต่างระดับ ตัวเครื่องออกแบบมาให้กะทัดรัดเป็นพิเศษและตั้งค่ามาจากโรงงานล่วงหน้า (pre-configured) จึงลดเวลาออกแบบและติดตั้ง พร้อมเข้ารับการทดสอบ FAT ได้ภายใน 3 เดือน

cGMP parts and glassware washer from the Fast-to-market Cleaning Systems range. 306-litre (11 ft³) chamber with a sliding-down door, available single or double for pass-through installation between classified areas. Extremely compact and factory pre-configured, shortening design and installation time — ready for FAT in 3 months.', '[{"label": "ปริมาตรห้องล้าง / Chamber volume", "value": "306 ลิตร (11 ft³)"}, {"label": "ประตู / Door type", "value": "Sliding Down — เลือกได้ทั้งประตูเดี่ยวและประตูคู่"}, {"label": "รูปแบบ / Configuration", "value": "กะทัดรัดเป็นพิเศษ ตั้งค่ามาจากโรงงาน (pre-configured)"}, {"label": "ระยะเวลาส่งมอบ / Lead time", "value": "พร้อมทดสอบ FAT ภายใน 3 เดือน"}, {"label": "กลุ่มสินค้า / Range", "value": "Fast-to-market Cleaning Systems — cGMP Parts and Glassware Washers"}, {"label": "แบรนด์ / Brand", "value": "SteelcoBelimed (Miele Group Member)"}]'::jsonb, 40),
  ('bioengineering-lp-p-fermenter', 'ถังหมัก/ถังปฏิกรณ์ชีวภาพ ระดับ⁠นำร่อง⁠ถึง⁠การ⁠ผลิต LP/P Series', 'LP/P Series Pilot & Production Fermenter', 'Bioengineering', 'Upstream Fermenter / Bioreactor', 'device', '🧬', '/products/bioengineering-lp-p-fermenter.jpg', 'The link between development and production', 'ถังหมักและถังปฏิกรณ์ชีวภาพสเตนเลสผนังสองชั้น สำหรับงานนำร่องและการผลิตปริมาณไม่มาก เป็นตัวเชื่อมระหว่างงานพัฒนากระบวนการกับสายการผลิตจริง ออกแบบบนแพลตฟอร์มเดียวกันทั้งซีรีส์ จึงปรับสเปกให้ตรงกับงานแต่ละแบบได้ยืดหยุ่น ระบบขับใบกวนจากด้านล่างพร้อมเพลาที่ถอดออกได้ง่ายช่วยให้ตัวถังเตี้ยลง เข้าถึงฝาถังและติดตั้งได้แม้ในห้องที่มีความสูงจำกัด งานเพาะเลี้ยงเซลล์รองรับ rotor filter สำหรับ perfusion การให้อากาศแบบไม่เกิดฟองสำหรับเซลล์ที่ไวต่อแรงเฉือน และการฆ่าเชื้อถังเปล่าสำหรับอาหารเลี้ยงเชื้อที่ไวต่อความร้อน ส่วนงานหมักจุลชีพมีระบบกวนกำลังสูงสำหรับจุลชีพที่ต้องการออกซิเจนมาก ใช้ได้ทั้งกระบวนการแบบแบตช์และแบบต่อเนื่อง เดินเครื่องแบบสแตนด์อโลนด้วยมือ หรือเดินอัตโนมัติเต็มรูปแบบผ่าน PLC ร่วมกับซอฟต์แวร์ BioSCADA มีเอกสารประกอบสำหรับงาน GMP

Double-wall stainless fermenter and bioreactor for pilot work and low-volume production — the link between process development and manufacturing. A shared platform across the series allows flexible adaptation to different requirements, and the bottom drive with an easily removable drive shaft keeps vessel height low for lid access and installation in rooms with limited headroom. Cell culture options include rotor filters for perfusion, bubble-free gassing for shear-sensitive cells and empty sterilisation for heat-sensitive media; microbial fermentation is served by powerful agitation systems for high oxygen demand. Suitable for batch and continuous processes, run manually as a stand-alone unit or fully automated via PLC with BioSCADA software. GMP documentation available.', '[{"label": "ปริมาตรใช้งาน / Working volume", "value": "ประมาณ 28 – 1,000 ลิตร (28 / 33 / 50 / 65 / 100 / 130 / 200 / 300 / 350 / 500 / 700 / 1000)"}, {"label": "ถัง / Vessel", "value": "สเตนเลส ผนังสองชั้น รวมถึงส่วนก้นถัง"}, {"label": "ระบบขับใบกวน / Drive", "value": "ขับจากด้านล่างด้วยสายพาน, double axial face seal, magnetic drive หรือขับจากด้านบน"}, {"label": "ใบกวน / Stirrers", "value": "Rushton, propeller, pitched-blade, vibromixer"}, {"label": "การให้อากาศ / Gassing", "value": "Ring / sinter sparger, surface gassing, bubble-free gassing — รองรับได้ถึง 8 สายก๊าซ ด้วย pulsed valve หรือ mass-flow controller"}, {"label": "การฆ่าเชื้อ / Sterilization", "value": "ไอน้ำและน้ำหล่อเย็น ฆ่าเชื้ออัตโนมัติทั้งแบบเต็มถังและถังเปล่า"}, {"label": "การจ่ายสาร / Dosing & transfer", "value": "จ่ายด้วยมือหรือควบคุมอัตโนมัติ, SteriCaps, ระบบวาล์วอัตโนมัติเต็มรูปแบบ, เลือกชนิดปั๊มได้หลายแบบ"}, {"label": "การวัดและควบคุม / Measurement", "value": "ความเร็วรอบ, อุณหภูมิ, pH, pO₂, antifoam/level, redox, OD, น้ำหนัก และการวิเคราะห์ก๊าซขาออก"}, {"label": "ซอฟต์แวร์ / Software", "value": "BioSCADA — ติดตามกระบวนการ จัดการข้อมูล รายงานแบตช์ profile, cascade และ sequencer ใช้งานได้โดยไม่ต้องเขียนโปรแกรม"}, {"label": "เอกสาร / Documentation", "value": "มีเอกสารประกอบสำหรับงาน GMP"}, {"label": "แบรนด์ / Brand", "value": "Bioengineering"}]'::jsonb, 50),
  ('pharmnxt-single-use-mixer', 'ระบบผสมแบบใช้ครั้งเดียว พร้อมถุงผสม (Single-Use Mixer)', 'Single-Use Mixer System with Mixing Bag', 'PharmNXT Biotech', 'Single-Use Mixer / Single-Use Bag', 'device', '🧫', '/products/pharmnxt-single-use-mixer.jpg', 'Closed-system mixing without cleaning', 'ระบบผสมของเหลวแบบใช้ครั้งเดียวสำหรับการเตรียมบัฟเฟอร์ อาหารเลี้ยงเชื้อ และการผสมสารละลายในกระบวนการผลิตชีววัตถุ ประกอบด้วยสองส่วนคือตัวเครื่องสเตนเลสที่ใช้ซ้ำได้ และถุงผสมแบบใช้ครั้งเดียวที่ประกอบสายและข้อต่อมาสำเร็จพร้อมใช้ ถุงจะถูกวางในโพรงของตัวเครื่องแล้วขับใบกวนจากด้านล่าง ของเหลวจึงสัมผัสเฉพาะพื้นผิวของถุงเท่านั้น ไม่ต้องล้างหรือฆ่าเชื้อเครื่องระหว่างแบตช์ ตัดขั้นตอน CIP/SIP และลดความเสี่ยงการปนเปื้อนข้ามผลิตภัณฑ์ ประตูบานคู่มีช่องมองสำหรับดูระดับและการผสมขณะทำงาน ควบคุมผ่านแผงควบคุมพร้อมจอแสดงผลที่ปรับตำแหน่งได้และปุ่มหยุดฉุกเฉิน ฐานเครื่องรองรับชุดชั่งน้ำหนักสำหรับจ่ายสารตามน้ำหนัก และมีล้อเลื่อนสำหรับย้ายจุดใช้งานในโรงงาน

Single-use mixing system for buffer and media preparation and in-process solution mixing. It pairs a reusable stainless station with a pre-assembled disposable mixing bag complete with tubing and connectors. The bag sits in the station''s cavity and the impeller is driven from below, so product contacts only the bag — no cleaning or sterilisation between batches, removing CIP/SIP steps and cross-product contamination risk. Twin doors with viewing windows show level and mixing during a run; an adjustable control terminal and emergency stop sit on the front, the base carries a weighing system for gravimetric dosing, and castors allow repositioning in the plant.', '[{"label": "รูปแบบ / Format", "value": "ตัวเครื่องสเตนเลสใช้ซ้ำ + ถุงผสมแบบใช้ครั้งเดียว"}, {"label": "ถุงผสม / Mixing bag", "value": "ประกอบสายและข้อต่อมาสำเร็จ พร้อมพอร์ตด้านบนและด้านล่าง"}, {"label": "ระบบกวน / Agitation", "value": "ขับใบกวนจากด้านล่างตัวเครื่อง ของเหลวสัมผัสเฉพาะถุง"}, {"label": "จุดเด่น / Key benefit", "value": "ไม่ต้องทำ CIP/SIP ระหว่างแบตช์ ลดความเสี่ยงปนเปื้อนข้ามผลิตภัณฑ์"}, {"label": "การมองเห็น / Visibility", "value": "ประตูบานคู่พร้อมช่องมอง ดูระดับและการผสมขณะทำงานได้"}, {"label": "การควบคุม / Control", "value": "แผงควบคุมพร้อมจอแสดงผลปรับตำแหน่งได้ และปุ่มหยุดฉุกเฉิน"}, {"label": "การชั่งน้ำหนัก / Weighing", "value": "ฐานเครื่องรองรับชุดชั่งน้ำหนัก สำหรับจ่ายสารตามน้ำหนัก"}, {"label": "การเคลื่อนย้าย / Mobility", "value": "มีล้อเลื่อน"}, {"label": "แบรนด์ / Brand", "value": "PharmNXT Biotech"}]'::jsonb, 60),
  ('lepure-single-use-mixer', 'ระบบผสมแบบใช้ครั้งเดียว พร้อมถุงบรรจุหลายขนาด', 'Single-Use Mixer & Single-Use Bags', 'Le Pure', 'Single-Use Mixer / Single-Use Bag', 'device', '🧫', '/products/lepure-single-use-mixer.jpg', 'Mobile mixing station with matched bag range', 'ระบบผสมแบบใช้ครั้งเดียวขนาดเคลื่อนย้ายได้ ประกอบด้วยสถานีผสมสเตนเลสที่ใช้ซ้ำได้ และถุงบรรจุแบบใช้ครั้งเดียวที่มีให้เลือกหลายขนาด ตั้งแต่ถุงเล็กสำหรับงานตัวอย่างและตั้งต้นการเลี้ยงเชื้อ ถุงกลางสำหรับเตรียมบัฟเฟอร์ ไปจนถึงถุงขนาดใหญ่สำหรับเก็บและถ่ายโอนของเหลวปริมาณมาก ทุกถุงประกอบสาย แคลมป์ และข้อต่อมาสำเร็จพร้อมใช้ ผ่านการฆ่าเชื้อมาแล้ว ตัวสถานีมีโพรงทรงเหลี่ยมสำหรับวางถุง ช่องกลมด้านข้างพร้อมฝาเปิดสำหรับเข้าถึงและตรวจสอบระหว่างใช้งาน ควบคุมผ่านหน้าจอสัมผัสขนาดใหญ่บนแขนที่ปรับตำแหน่งได้ตามความถนัดของผู้ใช้ ฐานเครื่องมีล้อเลื่อนสี่ล้อพร้อมล็อก ย้ายไปใช้ตามจุดต่าง ๆ ในสายการผลิตได้ ของเหลวสัมผัสเฉพาะพื้นผิวของถุงเท่านั้น จึงไม่ต้องล้างหรือฆ่าเชื้อเครื่องระหว่างแบตช์

Mobile single-use mixing system pairing a reusable stainless station with a range of disposable bags — from small bags for samples and seed steps, through mid-size bags for buffer preparation, to large bags for bulk storage and transfer. All bags come pre-assembled with tubing, clamps and connectors and pre-sterilised. The station has a squared cavity for the bag and a round access port with a hinged cover for inspection during a run; a large touchscreen on an adjustable arm sets operator position, and four locking castors allow moving along the line. Product contacts only the bag, so no cleaning or sterilisation is needed between batches.', '[{"label": "รูปแบบ / Format", "value": "สถานีผสมสเตนเลสใช้ซ้ำ + ถุงบรรจุแบบใช้ครั้งเดียว"}, {"label": "ขนาดถุง / Bag range", "value": "มีหลายขนาด ตั้งแต่ถุงตัวอย่างขนาดเล็กจนถึงถุงเก็บของเหลวขนาดใหญ่"}, {"label": "ถุงบรรจุ / Bag assembly", "value": "ประกอบสาย แคลมป์ และข้อต่อมาสำเร็จ ผ่านการฆ่าเชื้อพร้อมใช้"}, {"label": "การเข้าถึง / Access", "value": "ช่องกลมด้านข้างพร้อมฝาเปิด สำหรับเข้าถึงและตรวจสอบระหว่างใช้งาน"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสขนาดใหญ่บนแขนปรับตำแหน่งได้"}, {"label": "การเคลื่อนย้าย / Mobility", "value": "ล้อเลื่อนสี่ล้อพร้อมล็อก"}, {"label": "จุดเด่น / Key benefit", "value": "ไม่ต้องล้างหรือฆ่าเชื้อเครื่องระหว่างแบตช์"}, {"label": "แบรนด์ / Brand", "value": "Le Pure"}]'::jsonb, 70),
  ('ami-polymer-3d-single-use-bags', 'ถุงบรรจุแบบใช้ครั้งเดียวทรงสามมิติ (3D Single-Use Bags)', '3D Single-Use Bags', 'Ami Polymer', 'Single-Use Mixer / Single-Use Bag', 'tube', '🧫', '/products/ami-polymer-3d-single-use-bags.jpg', 'Cube-shaped bags for bulk liquid handling', 'ถุงบรรจุแบบใช้ครั้งเดียวขึ้นรูปทรงสามมิติ เมื่อบรรจุของเหลวแล้วจะตั้งทรงเป็นลูกบาศก์ ใช้พื้นที่จัดเก็บได้เต็มประสิทธิภาพกว่าถุงแบน และวางในถังหรือกล่องรองรับได้พอดี เหมาะกับการเก็บและถ่ายโอนของเหลวปริมาณมากในกระบวนการผลิตชีววัตถุ เช่น บัฟเฟอร์ อาหารเลี้ยงเชื้อ และผลิตภัณฑ์ระหว่างผลิต ตัวถุงประกอบสาย ข้อต่อ และแคลมป์มาสำเร็จพร้อมใช้ จึงต่อเข้ากับระบบได้โดยไม่ต้องประกอบเพิ่ม พร้อมป้ายฉลากบาร์โค้ดบนสายสำหรับระบุตัวตนและตรวจสอบย้อนกลับของแต่ละถุง

Three-dimensional single-use bags that take a cube shape once filled — using storage space more efficiently than flat bags and seating neatly into a supporting tote or shell. Suited to bulk storage and transfer of buffers, media and in-process product in biologics manufacturing. Supplied pre-assembled with tubing, connectors and clamps so they connect straight into the system, with a barcoded label on the line for per-bag identification and traceability.', '[{"label": "รูปแบบ / Format", "value": "ถุงทรงสามมิติ (3D) ตั้งทรงเป็นลูกบาศก์เมื่อบรรจุของเหลว"}, {"label": "การใช้งาน / Application", "value": "เก็บและถ่ายโอนบัฟเฟอร์ อาหารเลี้ยงเชื้อ และผลิตภัณฑ์ระหว่างผลิต"}, {"label": "ชุดสาย / Assembly", "value": "ประกอบสาย ข้อต่อ และแคลมป์มาสำเร็จพร้อมใช้"}, {"label": "การระบุตัวตน / Traceability", "value": "ป้ายฉลากพร้อมบาร์โค้ดประจำถุง"}, {"label": "การติดตั้ง / Support", "value": "ใช้ร่วมกับถังหรือกล่องรองรับ (tote / shell)"}, {"label": "แบรนด์ / Brand", "value": "Ami Polymer"}]'::jsonb, 80),
  ('lonza-ultramdck-medium', 'อาหารเลี้ยงเซลล์ปลอดซีรัม UltraMDCK สำหรับเซลล์ MDCK', 'BioWhittaker® UltraMDCK Serum-free Medium', 'Lonza', 'GMP Cell Culture Media for Protein Base', 'liquid', '🧫', '/products/lonza-ultramdck-medium.jpg', 'Serum-free medium for MDCK cells', 'อาหารเลี้ยงเซลล์สูตรปลอดซีรัม (serum-free) ที่พัฒนาสำหรับเซลล์สาย MDCK โดยเฉพาะ ซึ่งเป็นเซลล์ที่ใช้กันแพร่หลายในการผลิตวัคซีนไข้หวัดใหญ่และงานเพาะเลี้ยงไวรัส การไม่ใช้ซีรัมจากสัตว์ช่วยลดความเสี่ยงการปนเปื้อนจากแหล่งสัตว์ ลดความแปรปรวนระหว่างล็อต และทำให้ขั้นตอนการทำบริสุทธิ์ปลายน้ำง่ายขึ้นเพราะมีโปรตีนแปลกปลอมในน้ำเลี้ยงน้อยลง ตัวอาหารผ่านการกรองปลอดเชื้อมาแล้วพร้อมใช้ บรรจุขวดขนาด 1,000 มล. เก็บรักษาที่ 2–8 °C และต้องป้องกันแสง

Serum-free cell culture medium developed specifically for MDCK cells, the line widely used for influenza vaccine production and virus propagation. Removing animal serum lowers the risk of animal-sourced contamination, reduces lot-to-lot variability, and simplifies downstream purification by leaving fewer foreign proteins in the harvest. Supplied sterile filtered and ready to use in 1,000 ml bottles, stored at 2–8 °C and protected from light.', '[{"label": "ชื่อผลิตภัณฑ์ / Product", "value": "BioWhittaker® UltraMDCK"}, {"label": "ประเภท / Type", "value": "อาหารเลี้ยงเซลล์ปลอดซีรัม (serum-free) สำหรับเซลล์ MDCK"}, {"label": "รหัสสินค้า / Cat No.", "value": "BEBP12-749Q"}, {"label": "ปริมาตรบรรจุ / Volume", "value": "1,000 มล. ต่อขวด"}, {"label": "การเตรียม / Processing", "value": "ผ่านการกรองปลอดเชื้อ (sterile filtered) พร้อมใช้"}, {"label": "การเก็บรักษา / Storage", "value": "2–8 °C ป้องกันแสง"}, {"label": "แหล่งผลิต / Origin", "value": "ผลิตในประเทศเบลเยียม (Lonza, Verviers)"}, {"label": "แบรนด์ / Brand", "value": "Lonza"}]'::jsonb, 90),
  ('filtrox-single-use-depth-filter', 'ชุดกรองเชิงลึกแบบใช้ครั้งเดียว (Single-Use Depth Filter)', 'Single-Use Depth Filter Module', 'Filtrox', 'Liquid / Air Filtration', 'device', '💧', '/products/filtrox-single-use-depth-filter.jpg', 'Pre-sterilised single-use depth filtration', 'ชุดกรองเชิงลึกแบบใช้ครั้งเดียว บรรจุแผ่นกรองไว้ในถุงหุ้มปิดสนิทพร้อมสายซิลิโคนเสริมแรงต่อเข้า-ออกและสายระบายอากาศ มาพร้อมใช้งานทันทีโดยไม่ต้องล้างหรือฆ่าเชื้อเครื่องกรองก่อนใช้ จึงตัดขั้นตอน CIP/SIP และลดความเสี่ยงการปนเปื้อนข้ามแบตช์ เหมาะกับการกรองใสของเหลวและลดปริมาณจุลชีพในกระบวนการผลิตชีววัตถุที่ใช้ระบบ single-use ทั้งสาย

Pre-assembled single-use depth filter — the filter stack is enclosed in a sealed bag with reinforced silicone inlet, outlet and vent lines, ready to use with no pre-use cleaning or sterilisation. Eliminates CIP/SIP steps and cross-batch contamination risk, for clarification and bioburden reduction in fully single-use biologics trains.', '[{"label": "รูปแบบ / Format", "value": "ชุดกรองสำเร็จแบบใช้ครั้งเดียว ในถุงหุ้มปิดสนิท"}, {"label": "การเชื่อมต่อ / Connections", "value": "สายซิลิโคนเสริมแรง — ทางเข้า ทางออก และสายระบายอากาศ"}, {"label": "การใช้งาน / Application", "value": "กรองใสของเหลว และลดปริมาณจุลชีพ (bioburden reduction)"}, {"label": "จุดเด่น / Key benefit", "value": "ไม่ต้องทำ CIP/SIP ก่อนใช้ ลดความเสี่ยงปนเปื้อนข้ามแบตช์"}, {"label": "แบรนด์ / Brand", "value": "Filtrox"}]'::jsonb, 100),
  ('filtrox-discstar-modules', 'โมดูลกรองเชิงลึกแบบแผ่นซ้อน DISCSTAR®', 'DISCSTAR® Lenticular Depth Filter Modules', 'Filtrox', 'Liquid / Air Filtration', 'device', '💧', '/products/filtrox-discstar-modules.jpg', 'Lenticular depth filter modules', 'โมดูลกรองเชิงลึกแบบแผ่นกรองซ้อนเป็นชั้น (lenticular) ติดตั้งซ้อนกันบนแกนกลางภายในชุดกรองสเตนเลส เพิ่มพื้นที่กรองได้มากในพื้นที่ติดตั้งเท่าเดิม โดยเพิ่มหรือลดจำนวนโมดูลตามปริมาณงาน ใช้กรองใสของเหลวและลดปริมาณจุลชีพในกระบวนการผลิตยา ชีววัตถุ และเครื่องดื่ม ฐานชุดกรองยึดด้วยสลักหูหิ้วโดยรอบ เปิด-ปิดเพื่อเปลี่ยนโมดูลได้เร็วโดยไม่ต้องใช้เครื่องมือพิเศษ

Lenticular depth filter modules stacked on a central core inside a stainless housing — high filter area in a small footprint, scaled by adding or removing modules. Used for clarification and bioburden reduction in pharmaceutical, biologics and beverage processing. The housing base closes with swing bolts around the rim for quick, tool-free module changes.', '[{"label": "รูปแบบ / Format", "value": "โมดูลแผ่นกรองซ้อนชั้น (lenticular) ติดตั้งในชุดกรอง"}, {"label": "การปรับขนาด / Scalability", "value": "เพิ่ม–ลดจำนวนโมดูลตามปริมาณงาน"}, {"label": "การใช้งาน / Application", "value": "กรองใสของเหลว และลดปริมาณจุลชีพ"}, {"label": "ชุดกรอง / Housing", "value": "สเตนเลส ยึดด้วยสลักหูหิ้วโดยรอบ เปลี่ยนโมดูลได้เร็ว"}, {"label": "แบรนด์ / Brand", "value": "Filtrox"}]'::jsonb, 110),
  ('filtrox-plate-filter-press', 'เครื่องกรองแบบแผ่นอัด (Plate & Frame Filter Press)', 'Plate & Frame Sheet Filter Press', 'Filtrox', 'Liquid / Air Filtration', 'device', '💧', '/products/filtrox-plate-filter-press.jpg', 'Mobile sheet filtration unit', 'เครื่องกรองแบบแผ่นอัดชนิดเคลื่อนย้ายได้ ประกอบด้วยชุดแผ่นกรองเชิงลึกเรียงสลับกับเฟรมและอัดแน่นด้วยแกนหมุนมือ ปรับจำนวนแผ่นกรองได้ตามปริมาณงานและระดับความใสที่ต้องการ โครงสร้างสเตนเลสทั้งชุดพร้อมล้อเลื่อนและถาดรองน้ำหยด ย้ายไปใช้ตามจุดต่าง ๆ ในโรงงานได้ ติดตั้งเกจวัดความดันทั้งด้านเข้าและออกเพื่อดูความต่างของความดันคร่อมชุดกรองระหว่างเดินเครื่อง ข้อต่อและวาล์วเป็นแบบสุขอนามัย ถอดล้างได้ เหมาะกับงานกรองใสในกระบวนการผลิตยา ชีววัตถุ เครื่องดื่ม และงานนำร่องก่อนขยายกำลังการผลิต

Mobile plate-and-frame sheet filter — depth filter sheets alternating with frames, clamped by a hand-operated spindle. The number of sheets is set to match throughput and the clarity required. Fully stainless frame on castors with a drip tray for moving between points in the plant, inlet and outlet pressure gauges to follow differential pressure during a run, and sanitary connections and valves throughout. Suited to clarification in pharmaceutical, biologics and beverage processing and to pilot work ahead of scale-up.', '[{"label": "รูปแบบ / Format", "value": "เครื่องกรองแบบแผ่นอัด ชนิดเคลื่อนย้ายได้ มีล้อเลื่อนและถาดรองน้ำหยด"}, {"label": "สื่อกรอง / Filter media", "value": "แผ่นกรองเชิงลึก (depth filter sheets) เปลี่ยนได้"}, {"label": "การปรับขนาด / Scalability", "value": "เพิ่ม–ลดจำนวนแผ่นกรองตามปริมาณงาน"}, {"label": "การอัดแน่น / Clamping", "value": "แกนหมุนมือ ไม่ต้องใช้ระบบไฮดรอลิก"}, {"label": "การติดตามค่า / Monitoring", "value": "เกจวัดความดันด้านเข้าและด้านออก ดูความต่างของความดันได้"}, {"label": "โครงสร้าง / Construction", "value": "สเตนเลส พร้อมข้อต่อและวาล์วแบบสุขอนามัย"}, {"label": "แบรนด์ / Brand", "value": "Filtrox"}]'::jsonb, 120),
  ('lepure-vacuum-filter-unit', 'ชุดกรองสุญญากาศแบบขวด (Vacuum Filter Unit)', 'Vacuum Filter Unit', 'Le Pure', 'Liquid / Air Filtration', 'device', '💧', '/products/lepure-vacuum-filter-unit.jpg', 'Disposable bottle-top vacuum filtration', 'ชุดกรองสุญญากาศแบบใช้ครั้งเดียว ประกอบด้วยกรวยกรองด้านบนที่มีแผ่นเมมเบรนในตัว และขวดรองรับน้ำกรองพร้อมฝาปิด ต่อสายสุญญากาศเข้าที่พอร์ตด้านข้างเพื่อดูดของเหลวผ่านเมมเบรน ใช้กรองอาหารเลี้ยงเซลล์ บัฟเฟอร์ และสารละลายให้ปลอดเชื้อในงานเพาะเลี้ยงเซลล์และงานเตรียมตัวอย่าง กรวยมีสเกลบอกปริมาตร ผ่านการฆ่าเชื้อมาแล้วพร้อมใช้ ปิดฝาขวดเก็บของเหลวที่กรองแล้วได้ทันที

Disposable vacuum filtration unit — a graduated upper funnel with an integral membrane over a receiver bottle with cap. A side port takes the vacuum line to draw liquid through the membrane. Used to sterile-filter cell culture media, buffers and solutions; supplied pre-sterilised, and the receiver bottle can be capped for storage straight after filtration.', '[{"label": "รูปแบบ / Format", "value": "ชุดใช้ครั้งเดียว — กรวยกรองพร้อมเมมเบรน + ขวดรองรับพร้อมฝา"}, {"label": "การใช้งาน / Application", "value": "กรองอาหารเลี้ยงเซลล์ บัฟเฟอร์ และสารละลายให้ปลอดเชื้อ"}, {"label": "การต่อใช้งาน / Connection", "value": "พอร์ตต่อสายสุญญากาศด้านข้างฐานกรวย"}, {"label": "จุดเด่น / Key feature", "value": "กรวยมีสเกลบอกปริมาตร ผ่านการฆ่าเชื้อมาแล้วพร้อมใช้"}, {"label": "แบรนด์ / Brand", "value": "Le Pure"}]'::jsonb, 130),
  ('lepure-filter-capsules-cartridges', 'แคปซูลกรอง ไส้กรอง และชุดกรองสเตนเลส', 'Filter Capsules, Cartridges & Housings', 'Le Pure', 'Liquid / Air Filtration', 'device', '💧', '/products/lepure-filter-capsules-cartridges.jpg', 'Full filtration range from bench to production', 'ชุดผลิตภัณฑ์กรองครบไลน์สำหรับกระบวนการผลิตยาและชีววัตถุ ครอบคลุมตั้งแต่แคปซูลกรองแบบใช้ครั้งเดียวขนาดเล็กสำหรับงานทดลอง ไปจนถึงแคปซูลขนาดใหญ่และไส้กรองแบบพลีท (pleated cartridge) สำหรับสายการผลิตจริง พร้อมชุดกรองสเตนเลสสำหรับติดตั้งไส้กรอง ใช้ได้ทั้งการกรองของเหลวและการกรองอากาศ/ก๊าซ ขนาดที่ไล่ระดับกันทำให้ขยายกำลังการผลิตจากงานทดลองขึ้นสู่ระดับผลิตได้โดยใช้เมมเบรนชนิดเดียวกันตลอดสาย

A complete filtration range for pharmaceutical and biologics processing — from small single-use capsules for trials through to large capsules and pleated cartridges for production, plus stainless housings to hold them. Covers both liquid and air/gas filtration, and the stepped sizes let a process scale from bench trials to full production on the same membrane.', '[{"label": "ผลิตภัณฑ์ในกลุ่ม / Range", "value": "แคปซูลกรองใช้ครั้งเดียว, ไส้กรองแบบพลีท และชุดกรองสเตนเลส"}, {"label": "การใช้งาน / Application", "value": "กรองของเหลว และกรองอากาศ/ก๊าซ"}, {"label": "การขยายกำลังผลิต / Scale-up", "value": "มีขนาดไล่ระดับตั้งแต่งานทดลองถึงระดับผลิต"}, {"label": "ชุดกรอง / Housings", "value": "สเตนเลส พร้อมข้อต่อสุขอนามัยและวาล์วระบายอากาศ"}, {"label": "แบรนด์ / Brand", "value": "Le Pure"}]'::jsonb, 140),
  ('silicone-tubing-platinum', 'ท่อซิลิโคนเกรดฟาร์ม่า (Platinum-cured)', 'Platinum-Cured Silicone Tubing', 'Ami Polymer', 'Silicone Tubing / Connectors', 'tube', '🧬', '/products/297849.jpg', 'Pharma-grade platinum-cured silicone', 'ท่อซิลิโคนขึ้นรูปด้วยกระบวนการ platinum-cured เนื้อใส ไม่มีสารตกค้างจากตัวเร่งเปอร์ออกไซด์ ผิวภายในเรียบช่วยลดการเกาะของอนุภาคและจุลชีพ ยืดหยุ่นสูงและคืนตัวดี เหมาะกับการส่งถ่ายของเหลวในกระบวนการผลิตยาชีววัตถุ งานปั๊มรีดท่อ (peristaltic pump) และระบบ single-use ทนการฆ่าเชื้อด้วยไอน้ำและรังสีแกมมา มีหลายขนาดเส้นผ่านศูนย์กลางให้เลือกตามการใช้งาน

Platinum-cured silicone tubing — clear, free of peroxide catalyst residues, with a smooth bore that limits particle and microbial adhesion. Built for biopharma fluid transfer, peristaltic pumping and single-use assemblies; withstands steam and gamma sterilisation. Available in a range of bore sizes.', '[{"label": "วัสดุ / Material", "value": "Platinum-cured silicone"}, {"label": "มาตรฐานอ้างอิง / Compliance", "value": "USP Class VI, FDA 21 CFR 177.2600"}, {"label": "ช่วงอุณหภูมิ / Temperature", "value": "ประมาณ −60 ถึง 200 °C"}, {"label": "การฆ่าเชื้อ / Sterilisation", "value": "Autoclave และ Gamma irradiation"}, {"label": "ขนาด / Sizes", "value": "มีหลายขนาดเส้นผ่านศูนย์กลาง"}]'::jsonb, 150),
  ('tpe-tubing', 'ท่อ TPE สำหรับระบบ Single-Use', 'Thermoplastic Elastomer (TPE) Tubing', 'Ami Polymer', 'Silicone Tubing / Connectors', 'tube', '🧬', '/products/297847.jpg', 'Weldable tubing for closed systems', 'ท่อเทอร์โมพลาสติกอิลาสโตเมอร์สำหรับระบบ single-use รองรับการเชื่อมต่อแบบปลอดเชื้อด้วยเครื่อง sterile tube welder และการปิดผนึกด้วย tube sealer ทำให้ต่อและตัดสายได้โดยไม่เปิดระบบ มีค่าการซึมผ่านของก๊าซต่ำกว่าซิลิโคน จึงเหมาะกับการเก็บและลำเลียงของเหลวในระบบปิดและงานถ่ายโอนระหว่างถุงบรรจุ

TPE tubing for single-use processing — compatible with sterile tube welders and sealers so connections can be made and closed without breaching the system. Lower gas permeability than silicone, suited to closed-system storage and bag-to-bag transfer.', '[{"label": "วัสดุ / Material", "value": "Thermoplastic elastomer (TPE)"}, {"label": "จุดเด่น / Key feature", "value": "เชื่อมและซีลแบบปลอดเชื้อได้ (weldable / sealable)"}, {"label": "การฆ่าเชื้อ / Sterilisation", "value": "Gamma irradiation"}, {"label": "การใช้งาน / Application", "value": "ระบบ single-use และการถ่ายโอนในระบบปิด"}]'::jsonb, 160),
  ('silicone-hose', 'สายซิลิโคนผนังหนา (Silicone Hose)', 'Platinum-Cured Silicone Hose', 'Ami Polymer', 'Silicone Tubing / Connectors', 'tube', '🧬', '/products/297848.jpg', 'Heavy-duty transfer hose', 'สายซิลิโคนผนังหนาสำหรับงานถ่ายเทของเหลวปริมาณมากที่ต้องรับแรงดันหรือสุญญากาศ เช่น การถ่ายโอนระหว่างถัง งานล้างระบบ CIP/SIP และการต่อเข้ากับหัวจ่ายแบบสุขอนามัย ผลิตจากซิลิโคนเกรดฟาร์ม่าชนิดเดียวกับท่อขนาดเล็ก จึงใช้ร่วมกันในสายการผลิตเดียวได้ ทนการฆ่าเชื้อด้วยไอน้ำ

Thick-wall platinum-cured silicone hose for higher-volume transfer under pressure or vacuum — vessel-to-vessel transfer, CIP/SIP lines and sanitary fitting connections. Same pharma-grade silicone as the smaller tubing, so both can run in one process train.', '[{"label": "วัสดุ / Material", "value": "Platinum-cured silicone"}, {"label": "โครงสร้าง / Construction", "value": "ผนังหนา (มีรุ่นเสริมชั้นถักให้เลือก)"}, {"label": "การใช้งาน / Application", "value": "ถ่ายเทของเหลวแรงดัน–สุญญากาศ, CIP/SIP"}, {"label": "การฆ่าเชื้อ / Sterilisation", "value": "Autoclave / Steam-in-place"}]'::jsonb, 170),
  ('verdot-inplace-easypack-columns', 'คอลัมน์โครมาโทกราฟีระดับการผลิต InPlace™ / EasyPack™', 'InPlace™ and EasyPack™ Chromatography Columns', 'VERDOT', 'Downstream Ion Chromatography', 'device', '⚗️', '/products/verdot-chromatography-column.jpg', 'Packed-bed columns for downstream purification', 'คอลัมน์โครมาโทกราฟีสำหรับขั้นตอนการทำบริสุทธิ์ downstream ในการผลิตชีววัตถุ ตัวคอลัมน์เป็นท่อใสมองเห็นชั้นเรซินได้ตลอดความสูง ตรวจสภาพชั้นเรซินและฟองอากาศได้โดยไม่ต้องเปิดระบบ อะแดปเตอร์ด้านบนปรับระดับด้วยเกลียวขับมอเตอร์ ทำให้ตั้งความสูงของชั้นเรซินและอัดชั้นให้แน่นสม่ำเสมอได้อย่างควบคุมและทำซ้ำได้ในทุกแบตช์ ท่อและวาล์วเป็นแบบสุขอนามัยพร้อมชุดท่อสำหรับการบรรจุและถ่ายเรซินออก มีเกจวัดความดันและถังลดแรงกระแทกติดตั้งที่ตัวคอลัมน์ โครงฐานสเตนเลสมีล้อเลื่อนสี่ล้อพร้อมขาปรับระดับ ย้ายตำแหน่งในโรงงานได้

Process chromatography columns for downstream purification of biologics. The clear column tube keeps the packed bed visible over its full height, so bed condition and air can be checked without opening the system. A motor-driven screw adapter sets bed height and compresses the bed in a controlled, repeatable way batch to batch. Sanitary piping and valves include a packing and unpacking manifold; a pressure gauge and damping vessel are mounted on the column, and the stainless base runs on four castors with levelling feet.', '[{"label": "ประเภท / Type", "value": "คอลัมน์โครมาโทกราฟีแบบชั้นเรซินอัดแน่น (packed bed)"}, {"label": "ตัวคอลัมน์ / Column tube", "value": "ท่อใส มองเห็นชั้นเรซินได้ตลอดความสูง"}, {"label": "การปรับชั้นเรซิน / Bed adjustment", "value": "อะแดปเตอร์ปรับระดับด้วยเกลียวขับมอเตอร์ ทำซ้ำได้ทุกแบตช์"}, {"label": "ท่อและวาล์ว / Piping", "value": "แบบสุขอนามัย พร้อมชุดท่อสำหรับบรรจุและถ่ายเรซินออก"}, {"label": "การติดตามค่า / Monitoring", "value": "เกจวัดความดันและถังลดแรงกระแทกที่ตัวคอลัมน์"}, {"label": "โครงฐาน / Base frame", "value": "สเตนเลส มีล้อเลื่อนสี่ล้อและขาปรับระดับ"}, {"label": "การใช้งาน / Application", "value": "การทำบริสุทธิ์ downstream — ion exchange, affinity และอื่น ๆ"}, {"label": "แบรนด์ / Brand", "value": "VERDOT"}]'::jsonb, 180),
  ('ecolab-chromatography-resin', 'เรซินสำหรับโครมาโทกราฟีระดับการผลิต', 'Process Chromatography Resins', 'ECOLAB', 'Downstream Ion Chromatography Resin', 'kit', '⚗️', '/products/ecolab-chromatography-resin.jpg', 'Downstream purification media', 'เรซินสำหรับงานโครมาโทกราฟีในขั้นตอน downstream ของการผลิตชีววัตถุ ใช้แยกและทำบริสุทธิ์โปรตีนเป้าหมายออกจากสิ่งเจือปน โดยบรรจุลงคอลัมน์แล้วใช้งานร่วมกับระบบโครมาโทกราฟีของสายการผลิต ผู้ผลิตมีห้องปฏิบัติการสำหรับทดสอบการบรรจุคอลัมน์และประเมินประสิทธิภาพของเรซินในคอลัมน์ขนาดเล็กก่อน แล้วจึงขยายขนาดขึ้นสู่คอลัมน์ระดับการผลิตด้วยเงื่อนไขเดียวกัน ช่วยลดความเสี่ยงและระยะเวลาในการปรับกระบวนการหน้างาน

Chromatography resins for the downstream stage of biologics manufacturing, separating and purifying the target protein from impurities once packed into a column and run on the process chromatography system. The manufacturer''s laboratory supports column packing trials and resin performance evaluation at small scale before scaling to production columns under the same conditions, reducing risk and process-tuning time on site.', '[{"label": "ประเภท / Type", "value": "เรซินสำหรับโครมาโทกราฟี (downstream purification)"}, {"label": "การใช้งาน / Application", "value": "แยกและทำบริสุทธิ์โปรตีนและชีววัตถุ"}, {"label": "การขยายขนาด / Scale-up", "value": "ทดสอบในคอลัมน์ขนาดเล็กก่อนขยายสู่คอลัมน์ระดับการผลิต"}, {"label": "บริการสนับสนุน / Support", "value": "บริการทดสอบการบรรจุคอลัมน์และประเมินประสิทธิภาพเรซิน"}, {"label": "แบรนด์ / Brand", "value": "ECOLAB"}]'::jsonb, 190),
  ('sus-ross-pftu', 'ระบบแช่แข็งและละลายแบบเพลต RoSS.pFTU', 'RoSS.pFTU Plate Freeze-Thaw Unit', 'Single Use Support', 'Advanced Fluid & Cold Chain Management', 'device', '❄️', '/products/sus-ross-pftu.jpg', 'Controlled plate freezing & thawing', 'ระบบแช่แข็งและละลายของเหลวชีวภาพแบบควบคุมอัตรา ใช้เพลตแลกเปลี่ยนความร้อนประกบถุงบรรจุแบบใช้ครั้งเดียวที่อยู่ในเปลือกป้องกัน (shell) ทั้งสองด้าน จึงถ่ายเทความเย็นและความร้อนได้สม่ำเสมอทั่วทั้งถุงและควบคุมอัตราการแช่แข็ง–ละลายได้แม่นยำ ช่วยรักษาคุณภาพของยาชีววัตถุและลดความเสียหายจากการเกิดผลึกน้ำแข็ง ตัวเครื่องเปิดฝาด้านบนเพื่อสอดถุงเข้าระหว่างเพลตทีละชั้น ควบคุมและติดตามรอบการทำงานผ่านหน้าจอสัมผัสที่ตู้ควบคุมด้านข้าง ตัวเครื่องมีล้อเลื่อน ย้ายตำแหน่งในโรงงานได้

Controlled-rate freezing and thawing platform for biologics. Heat-exchange plates contact both sides of single-use bags held in protective shells, giving uniform heat transfer across the bag and precise control of freeze and thaw rates — protecting product quality and limiting ice-crystal damage. The lid opens from the top to load bags between the plate stack; cycles are run and monitored from the touchscreen on the side control cabinet. Mounted on castors for repositioning within the plant.', '[{"label": "หลักการ / Principle", "value": "แช่แข็ง–ละลายแบบควบคุมอัตราด้วยเพลตแลกเปลี่ยนความร้อนประกบสองด้าน"}, {"label": "ภาชนะบรรจุ / Container", "value": "ถุงบรรจุแบบใช้ครั้งเดียวในเปลือกป้องกัน (shell)"}, {"label": "การโหลด / Loading", "value": "เปิดฝาด้านบน สอดถุงเข้าระหว่างชั้นเพลต"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสที่ตู้ควบคุม ติดตามและบันทึกรอบการทำงาน"}, {"label": "การเคลื่อนย้าย / Mobility", "value": "มีล้อเลื่อน"}, {"label": "แบรนด์ / Brand", "value": "Single Use Support"}]'::jsonb, 200),
  ('sus-ross-pftu-compact', 'ระบบแช่แข็งและละลายแบบเพลต RoSS.pFTU (รุ่นคอมแพ็กต์)', 'RoSS.pFTU Plate Freeze-Thaw Unit — Compact', 'Single Use Support', 'Advanced Fluid & Cold Chain Management', 'device', '❄️', '/products/sus-ross-pftu-compact.jpg', 'Compact freeze-thaw for development scale', 'รุ่นขนาดกะทัดรัดของระบบแช่แข็งและละลายแบบเพลต สำหรับงานพัฒนากระบวนการและการผลิตปริมาณน้อย ใช้หลักการเดียวกับรุ่นใหญ่คือเพลตแลกเปลี่ยนความร้อนประกบถุงบรรจุแบบใช้ครั้งเดียวทั้งสองด้าน จึงทำ scale-up ต่อไปยังรุ่นใหญ่ได้โดยใช้โปรไฟล์อุณหภูมิเดียวกัน ตู้ควบคุมรวมหน้าจอสัมผัสและชุดทำความเย็นไว้ในตัว ใช้พื้นที่ติดตั้งน้อย และมีปุ่มหยุดฉุกเฉินที่หน้าเครื่อง

Compact version of the plate freeze-thaw platform for process development and small-volume production. Same plate-contact principle as the larger units, so temperature profiles transfer directly when scaling up. Control cabinet integrates the touchscreen and refrigeration unit in a small footprint, with an emergency stop on the front panel.', '[{"label": "หลักการ / Principle", "value": "แช่แข็ง–ละลายแบบควบคุมอัตราด้วยเพลตแลกเปลี่ยนความร้อน"}, {"label": "ขนาด / Scale", "value": "รุ่นคอมแพ็กต์ สำหรับงานพัฒนากระบวนการและการผลิตปริมาณน้อย"}, {"label": "การขยายกำลังผลิต / Scale-up", "value": "ใช้โปรไฟล์อุณหภูมิร่วมกับรุ่นใหญ่ได้"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสในตู้ควบคุม พร้อมปุ่มหยุดฉุกเฉิน"}, {"label": "การเคลื่อนย้าย / Mobility", "value": "มีล้อเลื่อน"}, {"label": "แบรนด์ / Brand", "value": "Single Use Support"}]'::jsonb, 210),
  ('sus-freeze-thaw-chamber', 'ตู้แช่แข็ง/ละลายขนาดใหญ่สำหรับถุงบรรจุแบบใช้ครั้งเดียว', 'Large-Scale Freeze-Thaw Chamber for Single-Use Bags', 'Single Use Support', 'Advanced Fluid & Cold Chain Management', 'device', '❄️', '/products/sus-freeze-thaw-chamber.jpg', 'Rack-loaded bulk freeze & thaw', 'ตู้แช่แข็งและละลายขนาดใหญ่สำหรับงานผลิตจริง ภายในเป็นชั้นวางบรรจุถุงบรรจุแบบใช้ครั้งเดียวที่อยู่ในเปลือกป้องกันหลายสิบใบต่อรอบ ทำให้แช่แข็งหรือละลายทั้งแบตช์ได้ในครั้งเดียวโดยแต่ละถุงได้รับสภาวะเดียวกัน ประตูบานใหญ่พร้อมซีลรอบวงและมือหมุนล็อกสองจุด ฐานตู้ออกแบบเป็นแบบพาเลทมีช่องสอดงารถโฟล์คลิฟท์ ย้ายทั้งตู้ได้ ด้านบนมีไฟสัญญาณแสดงสถานะการทำงาน

Large-scale freeze-thaw chamber for production. An internal rack holds dozens of shell-protected single-use bags per run, so a whole batch is frozen or thawed together under identical conditions. Large gasketed door with two lever locks; the pallet-style base with fork channels lets the complete unit be moved, and a status beacon sits on top of the cabinet.', '[{"label": "รูปแบบ / Format", "value": "ตู้ขนาดใหญ่ ภายในเป็นชั้นวางบรรจุหลายใบต่อรอบ"}, {"label": "ภาชนะบรรจุ / Container", "value": "ถุงบรรจุแบบใช้ครั้งเดียวในเปลือกป้องกัน (shell)"}, {"label": "จุดเด่น / Key benefit", "value": "แช่แข็ง–ละลายทั้งแบตช์พร้อมกัน ทุกถุงได้รับสภาวะเดียวกัน"}, {"label": "ประตู / Door", "value": "บานใหญ่พร้อมซีลรอบวง ล็อกด้วยมือหมุนสองจุด"}, {"label": "การเคลื่อนย้าย / Handling", "value": "ฐานแบบพาเลท มีช่องสอดงารถโฟล์คลิฟท์"}, {"label": "การแสดงสถานะ / Status", "value": "ไฟสัญญาณด้านบนตู้"}, {"label": "แบรนด์ / Brand", "value": "Single Use Support"}]'::jsonb, 220),
  ('pharmnxt-automated-bioprocessing', 'ระบบกระบวนการชีวภาพอัตโนมัติ (Automated Bioprocessing System)', 'Automated Bioprocessing System', 'PharmNXT Biotech', 'Bioprocess Equipment', 'device', '⚙️', '/products/pharmnxt-automated-bioprocessing.jpg', 'Skid-mounted automated processing unit', 'ชุดอุปกรณ์กระบวนการชีวภาพแบบอัตโนมัติบนโครงเคลื่อนย้ายได้ ตัวตู้สเตนเลสบรรจุระบบไฟฟ้าและอุปกรณ์ควบคุมไว้ภายใน ปิดล็อกได้เพื่อป้องกันการเข้าถึงโดยไม่ได้รับอนุญาต แผงควบคุมด้านบนออกแบบเป็นมุมเอียงให้อ่านและใช้งานได้สะดวกขณะยืน ประกอบด้วยหน้าจอสัมผัสสำหรับตั้งค่าและติดตามกระบวนการ ปุ่มเดินเครื่องและหยุด พร้อมปุ่มหยุดฉุกเฉินที่ด้านข้างตู้ ไฟสัญญาณสามสีด้านบนแสดงสถานะการทำงานให้เห็นจากระยะไกล ด้านข้างมีรางแนวตั้งพร้อมแคลมป์สำหรับยึดสาย ไส้กรอง และหัววัดให้เข้าที่ระหว่างเดินกระบวนการ ฐานเครื่องมีล้อเลื่อนสำหรับย้ายไปใช้ตามจุดต่าง ๆ ในสายการผลิต

Skid-mounted automated bioprocessing unit. The stainless cabinet houses the electrical and control hardware behind lockable doors, with an angled top panel for comfortable standing operation — touchscreen for setting up and following the process, run and stop buttons, and an emergency stop on the side. A three-colour beacon shows status from across the room. A vertical rail on the side carries clamps to hold tubing, filters and probes in place during a run, and the base runs on castors for moving along the line.', '[{"label": "รูปแบบ / Format", "value": "ตู้ควบคุมสเตนเลสบนโครงเคลื่อนย้ายได้"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสบนแผงเอียง พร้อมปุ่มเดินเครื่อง หยุด และหยุดฉุกเฉิน"}, {"label": "การแสดงสถานะ / Status", "value": "ไฟสัญญาณสามสีด้านบนตู้"}, {"label": "โครงยึดอุปกรณ์ / Fixtures", "value": "รางแนวตั้งพร้อมแคลมป์ ยึดสาย ไส้กรอง และหัววัด"}, {"label": "ความปลอดภัย / Safety", "value": "ตู้ปิดล็อกได้ พร้อมสวิตช์ตัดตอนหลักที่หน้าตู้"}, {"label": "การเคลื่อนย้าย / Mobility", "value": "ล้อเลื่อน"}, {"label": "แบรนด์ / Brand", "value": "PharmNXT Biotech"}]'::jsonb, 230),
  ('pharmnxt-tff-system', 'ระบบกรองแบบไหลขวาง (TFF) ทั้งแบบ Single-Use และสเตนเลส', 'Single-Use and Stainless Steel Tangential Flow Filtration System', 'PharmNXT Biotech', 'Bioprocess Equipment', 'device', '⚙️', '/products/pharmnxt-tff-system.jpg', 'Concentration & diafiltration skid', 'ระบบกรองแบบไหลขวาง (Tangential Flow Filtration) สำหรับขั้นตอนเพิ่มความเข้มข้นของสารละลายและการเปลี่ยนบัฟเฟอร์ (diafiltration) ในกระบวนการผลิตชีววัตถุ ประกอบด้วยถังพักรีเทนเทตพร้อมฝาหลายพอร์ตสำหรับติดตั้งหัววัดและสายป้อน ชุดยึดเมมเบรนแบบแคสเซ็ตต์ที่ปรับแรงอัดได้ ปั๊มส่งของเหลว และชุดวัดความดันบนสาย feed, retentate และ permeate เพื่อควบคุมความดันคร่อมเมมเบรน (TMP) ตลอดรอบการทำงาน เลือกทางเดินของเหลวได้ทั้งแบบ single-use ที่ไม่ต้องล้างระหว่างแบตช์ และแบบสเตนเลสสำหรับงานที่เดินซ้ำต่อเนื่อง ควบคุมผ่านหน้าจอสัมผัสขนาดใหญ่ที่ติดตั้งบนแขนหมุน พร้อมไฟสัญญาณแสดงสถานะ โครงเครื่องมีล้อเลื่อนสำหรับย้ายจุดใช้งาน

Tangential flow filtration system for concentration and diafiltration in biologics manufacturing. It combines a retentate vessel with a multi-port lid for probes and feed lines, an adjustable cassette holder for the TFF membranes, a process pump, and pressure measurement on the feed, retentate and permeate lines to hold transmembrane pressure through the run. The flow path is available as single-use — no cleaning between batches — or in stainless steel for repeated campaigns. A large touchscreen on a swing arm runs the system, with a status beacon alongside, and the frame moves on castors.', '[{"label": "ประเภท / Type", "value": "ระบบกรองแบบไหลขวาง (Tangential Flow Filtration)"}, {"label": "ทางเดินของเหลว / Flow path", "value": "เลือกได้ทั้งแบบ single-use และสเตนเลส"}, {"label": "การใช้งาน / Application", "value": "เพิ่มความเข้มข้น (concentration) และเปลี่ยนบัฟเฟอร์ (diafiltration)"}, {"label": "ถังพัก / Vessel", "value": "ถังรีเทนเทตพร้อมฝาหลายพอร์ตสำหรับหัววัดและสายป้อน"}, {"label": "ชุดเมมเบรน / Membrane holder", "value": "แคสเซ็ตต์โฮลเดอร์ปรับแรงอัดได้"}, {"label": "การวัดและควบคุม / Monitoring", "value": "วัดความดันบนสาย feed, retentate และ permeate เพื่อควบคุม TMP"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสขนาดใหญ่บนแขนหมุน พร้อมไฟสัญญาณสถานะ"}, {"label": "การเคลื่อนย้าย / Mobility", "value": "โครงเครื่องมีล้อเลื่อน"}, {"label": "แบรนด์ / Brand", "value": "PharmNXT Biotech"}]'::jsonb, 240),
  ('protak-pr2a-enzyme-indicator-reader', 'เครื่องตรวจสอบความถูกต้องของการพ่นฆ่าเชื้อด้วยไฮโดรเจนเปอร์ออกไซด์แบบรวดเร็วด้วยเอ็นไซม์อินดิเคเตอร์', 'PR2A Enzyme Indicator Reader', 'Protak Scientific', 'Rapid Validation Enzyme Indicator', 'device', '🧪', '/products/protak-pr2a-reader.jpg', 'Rapid bio-decontamination cycle validation', 'เครื่องอ่านผลตัวชี้วัดเอนไซม์แบบตั้งโต๊ะ สำหรับตรวจสอบประสิทธิผลของรอบการฆ่าเชื้อในไอโซเลเตอร์ ห้องสะอาด และตู้ส่งผ่าน โดยใช้ตัวชี้วัดชนิดเอนไซม์แทนตัวชี้วัดชีวภาพแบบเดิม จึงทราบผลได้ภายในเวลาอันสั้นแทนที่จะต้องรอบ่มเชื้อหลายวัน ช่วยย่นระยะเวลาการพัฒนาและตรวจสอบรอบการฆ่าเชื้อได้อย่างมาก ตัวเครื่องมีช่องใส่ตัวอย่างด้านหน้า และหัวฉีดน้ำยาสองช่อง (Injector 1 สำหรับ ATP และ Injector 2) ต่อสายเข้ากับขวดน้ำยาที่วางบนแท่นข้างเครื่อง ระบบจ่ายน้ำยาให้อัตโนมัติในจังหวะที่กำหนด ทำให้ผลการวัดสม่ำเสมอและทำซ้ำได้

Bench-top reader for enzyme indicators used to verify bio-decontamination cycles in isolators, cleanrooms and pass-through chambers. Enzyme indicators replace conventional biological indicators, returning a result in a short time instead of days of incubation — cutting cycle development and verification time substantially. The unit has a front sample port and two reagent injectors (Injector 1 for ATP and Injector 2) fed from reagent vials on the adjacent rack, dispensed automatically at set points in the read so results stay consistent and repeatable.', '[{"label": "รูปแบบ / Format", "value": "เครื่องอ่านผลแบบตั้งโต๊ะ"}, {"label": "รุ่นในภาพ / Model shown", "value": "PR2A"}, {"label": "ระบบจ่ายน้ำยา / Injectors", "value": "หัวฉีด 2 ช่อง — Injector 1 (ATP) และ Injector 2 พร้อมขวดน้ำยาต่อสายเข้าเครื่อง"}, {"label": "ช่องใส่ตัวอย่าง / Sample port", "value": "ช่องด้านหน้าซ้ายของตัวเครื่อง"}, {"label": "การใช้งาน / Application", "value": "ตรวจสอบรอบการฆ่าเชื้อของไอโซเลเตอร์ ห้องสะอาด และตู้ส่งผ่าน"}, {"label": "จุดเด่น / Key benefit", "value": "ทราบผลเร็วกว่าตัวชี้วัดชีวภาพที่ต้องรอบ่มเชื้อหลายวัน"}, {"label": "แบรนด์ / Brand", "value": "Protak Scientific"}]'::jsonb, 250),
  ('qjet-ct10', 'เครื่องพ่นฆ่าเชื้อละอองแห้ง Q-Jet CT10', 'Q-Jet CT10 Dry-Fog Disinfection Unit', 'Sanosil', 'Surface Disinfection', 'device', '🛡️', '/products/297475.jpg', 'Portable dry-fog fogger', 'เครื่องพ่นละอองแห้ง (dry fog) แบบเคลื่อนย้ายได้ สำหรับฆ่าเชื้อพื้นผิวและอากาศในห้องสะอาด ห้องผลิต ห้องเก็บของ และพื้นที่ควบคุม ใช้คู่กับน้ำยา Sanosil S015 โดยติดตั้งขวดน้ำยาเข้ากับตัวเครื่องโดยตรง ตั้งเวลาและปริมาณการพ่นได้จากแผงควบคุมดิจิทัล พร้อมไฟสัญญาณเตือนขณะเครื่องทำงาน

Portable dry-fog aerosol generator for surface and airborne disinfection of cleanrooms and controlled areas. Runs on Sanosil S015 with an on-board solution bottle, digital timer control and a warning beacon during operation.', '[{"label": "รูปแบบ / Format", "value": "เครื่องตั้งพื้นแบบเคลื่อนย้ายได้ (portable)"}, {"label": "น้ำยาที่ใช้ / Solution", "value": "Sanosil S015"}, {"label": "การควบคุม / Control", "value": "แผงควบคุมดิจิทัล ตั้งเวลาและปริมาณการพ่น"}, {"label": "ความปลอดภัย / Safety", "value": "ไฟสัญญาณเตือนขณะทำงาน"}]'::jsonb, 260),
  ('qjet-ct20', 'เครื่องพ่นฆ่าเชื้อละอองแห้ง Q-Jet CT20', 'Q-Jet CT20 Dry-Fog Disinfection Unit', 'Sanosil', 'Surface Disinfection', 'device', '🛡️', '/products/297476.jpg', 'Mobile dry-fog system for large areas', 'รุ่นความจุสูงแบบมีล้อลาก สำหรับฆ่าเชื้อพื้นที่ขนาดใหญ่หรือพ่นต่อเนื่องหลายห้อง ถังบรรจุน้ำยาในตัวช่วยลดจำนวนครั้งในการเติม เหมาะกับงานฆ่าเชื้อประจำรอบในโรงงานผลิตยา คลังสินค้า และพื้นที่สะอาดขนาดใหญ่ ใช้น้ำยา Sanosil S015 เช่นเดียวกับรุ่น CT10

Higher-capacity, trolley-mounted dry-fog unit for large rooms or back-to-back room cycles. Built-in solution reservoir reduces refills; uses the same Sanosil S015 solution as the CT10.', '[{"label": "รูปแบบ / Format", "value": "แบบมีล้อลาก เคลื่อนย้ายระหว่างห้องได้"}, {"label": "น้ำยาที่ใช้ / Solution", "value": "Sanosil S015"}, {"label": "เหมาะกับ / Application", "value": "ห้องขนาดใหญ่ / พ่นต่อเนื่องหลายห้อง"}, {"label": "การควบคุม / Control", "value": "ตั้งเวลาและปริมาณการพ่น"}]'::jsonb, 270),
  ('sanosil-s015-1kg', 'น้ำยาฆ่าเชื้อ Sanosil S015 ขนาด 1 กก.', 'Sanosil S015 Disinfectant — 1 kg', 'Sanosil', 'Surface Disinfection', 'liquid', '🧴', '/products/297837.jpg', 'Hydrogen peroxide + silver disinfectant', 'น้ำยาฆ่าเชื้อสูตรไฮโดรเจนเปอร์ออกไซด์ที่เสถียรด้วยซิลเวอร์ (H₂O₂ + Ag) ไม่มีสี ไม่มีกลิ่นตกค้าง และสลายตัวเป็นน้ำกับออกซิเจนหลังใช้งาน ใช้ได้ทั้งการพ่นละอองแห้งด้วยเครื่อง Q-Jet และการเช็ดพื้นผิวโดยตรง เหมาะกับห้องสะอาด ห้องผลิต พื้นผิวอุปกรณ์ และระบบน้ำ ขนาดบรรจุ 1 กก. เหมาะกับการใช้งานรายวันหรือพื้นที่ขนาดเล็ก

Silver-stabilised hydrogen peroxide disinfectant — colourless, odourless and residue-free, decomposing into water and oxygen. Suitable for Q-Jet dry fogging and manual surface wiping. 1 kg pack for daily use or smaller areas.', '[{"label": "สารออกฤทธิ์ / Active", "value": "Hydrogen peroxide เสถียรด้วยซิลเวอร์ (H₂O₂ + Ag)"}, {"label": "ขนาดบรรจุ / Pack size", "value": "1 กก. (ขวด)"}, {"label": "วิธีใช้ / Method", "value": "พ่นละอองแห้งด้วย Q-Jet หรือเช็ดพื้นผิว"}, {"label": "สารตกค้าง / Residue", "value": "สลายตัวเป็นน้ำและออกซิเจน"}]'::jsonb, 280),
  ('sanosil-s015-5kg', 'น้ำยาฆ่าเชื้อ Sanosil S015 ขนาด 5 กก.', 'Sanosil S015 Disinfectant — 5 kg', 'Sanosil', 'Surface Disinfection', 'liquid', '🧴', '/products/297840.jpg', 'Bulk pack for routine disinfection', 'น้ำยาฆ่าเชื้อ Sanosil S015 สูตรเดียวกับขนาดขวด แต่บรรจุในแกลลอนสำหรับการใช้งานปริมาณมาก เหมาะกับโรงงานผลิตยาและอาหารที่มีรอบการฆ่าเชื้อประจำ หรือใช้เติมเครื่องพ่น Q-Jet CT20 แกลลอนทึบแสงช่วยรักษาความคงตัวของน้ำยาระหว่างจัดเก็บ

The same Sanosil S015 formulation in a bulk canister for routine, high-volume disinfection programmes and for refilling the Q-Jet CT20. Opaque canister protects solution stability during storage.', '[{"label": "สารออกฤทธิ์ / Active", "value": "Hydrogen peroxide เสถียรด้วยซิลเวอร์ (H₂O₂ + Ag)"}, {"label": "ขนาดบรรจุ / Pack size", "value": "5 กก. (แกลลอน)"}, {"label": "วิธีใช้ / Method", "value": "เติมเครื่องพ่น Q-Jet หรือผสมใช้เช็ดพื้นผิว"}, {"label": "การจัดเก็บ / Storage", "value": "แกลลอนทึบแสง เก็บในที่เย็นและพ้นแสงแดด"}]'::jsonb, 290),
  ('sanosil-test-strips', 'ชุดทดสอบความเข้มข้นน้ำยา Sanosil (Test Strips)', 'Sanosil Peroxide Test Strips', 'Sanosil', 'Surface Disinfection', 'kit', '🧫', '/products/297842.jpg', 'Verify working solution concentration', 'แถบทดสอบสำหรับตรวจวัดความเข้มข้นของไฮโดรเจนเปอร์ออกไซด์ในสารละลาย Sanosil ที่เจือจางแล้ว ใช้ยืนยันความเข้มข้นของน้ำยาก่อนใช้งานจริง และเก็บผลเป็นหลักฐานการควบคุมคุณภาพตามระบบ GMP อ่านผลด้วยการเทียบสีกับแถบสีมาตรฐานบนกระปุก ไม่ต้องใช้เครื่องมือเพิ่ม

Colorimetric strips for checking hydrogen peroxide concentration in diluted Sanosil working solution — a quick QC check before use, readable against the colour chart on the tube with no instrument required.', '[{"label": "รูปแบบ / Format", "value": "แถบทดสอบอ่านผลด้วยการเทียบสี"}, {"label": "ใช้วัด / Measures", "value": "ความเข้มข้นไฮโดรเจนเปอร์ออกไซด์ในสารละลายใช้งาน"}, {"label": "การใช้งาน / Use", "value": "ตรวจก่อนใช้งานและบันทึกเป็นหลักฐาน QC"}]'::jsonb, 300),
  ('microbial-air-sampler', 'เครื่องเก็บตัวอย่างอากาศเชิงจุลชีววิทยา', 'Microbial Air Sampler', NULL, 'Air Sampler / Environmental Monitoring', 'air', '💨', '/products/297846.jpg', 'Cleanroom environmental monitoring', 'เครื่องเก็บตัวอย่างอากาศแบบ impaction ลงบนจานเลี้ยงเชื้อ สำหรับงานตรวจติดตามสภาพแวดล้อม (Environmental Monitoring) ในห้องสะอาดและพื้นที่ปลอดเชื้อ ตั้งปริมาตรอากาศและเวลาเก็บตัวอย่างได้จากแป้นควบคุม ตัวเรือนออกแบบให้เช็ดฆ่าเชื้อและถอดฝาครอบทำความสะอาดได้ง่าย

Impaction-type microbial air sampler collecting onto agar plates for cleanroom environmental monitoring. Programmable sample volume and duration; wipe-down housing with removable sampling head.', '[{"label": "หลักการ / Principle", "value": "Impaction ลงบนจานเลี้ยงเชื้อ (agar plate)"}, {"label": "การตั้งค่า / Settings", "value": "ตั้งปริมาตรอากาศและเวลาเก็บตัวอย่างได้"}, {"label": "การใช้งาน / Application", "value": "EM ห้องสะอาด Grade A–D"}]'::jsonb, 310),
  ('filter-integrity-tester-v8', 'เครื่องทดสอบความสมบูรณ์ของไส้กรอง V8.0', 'Filter Integrity Tester V8.0', 'Neuronbc', 'Filter Integrity Tester, Packing Leak Tester, Glove Integrity Test, Bag Integrity Tester', 'device', '🧪', '/products/filter-integrity-tester.jpg', 'Automated filter integrity testing', 'เครื่องทดสอบความสมบูรณ์ของไส้กรองแบบอัตโนมัติ ใช้ตรวจสอบไส้กรองระดับ sterilizing-grade ทั้งก่อนและหลังการกรอง (pre-use / post-use) ตามข้อกำหนด GMP ควบคุมผ่านหน้าจอสัมผัส บันทึกผลการทดสอบพร้อมชื่อผู้ทดสอบและวันเวลาเพื่อการตรวจสอบย้อนกลับ ต่อพอร์ตทดสอบได้หลายช่องบนตัวเครื่อง

Automated integrity tester for sterilizing-grade filters, supporting pre-use and post-use testing under GMP. Touchscreen control with user login, stored test records and printable reports for full traceability.', '[{"label": "วิธีทดสอบ / Test methods", "value": "Bubble Point, Diffusion Flow, Water Intrusion Test"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสสี พร้อมระบบล็อกอินผู้ใช้"}, {"label": "การบันทึกผล / Records", "value": "จัดเก็บผลทดสอบในเครื่อง และพิมพ์รายงานได้"}, {"label": "การเชื่อมต่อ / Ports", "value": "พอร์ตทดสอบหลายช่องด้านข้างตัวเครื่อง"}]'::jsonb, 320),
  ('glove-integrity-tester-gt2', 'เครื่องทดสอบความสมบูรณ์ของถุงมือไอโซเลเตอร์ GT-2.0', 'Glove Integrity Tester GT-2.0', 'Neuronbc', 'Filter Integrity Tester, Packing Leak Tester, Glove Integrity Test, Bag Integrity Tester', 'device', '🧤', '/products/297844.jpg', 'Isolator glove leak testing', 'เครื่องทดสอบการรั่วของถุงมือในไอโซเลเตอร์และ RABS ด้วยหลักการ pressure decay ตัวเครื่องแบบติดผนังพร้อมหน้าจอสัมผัส รองรับการยืนยันตัวตนผู้ใช้ด้วยการแตะบัตร (NFC) ก่อนเริ่มทดสอบ เก็บผลการทดสอบรายถุงมือเพื่อใช้เป็นหลักฐานการตรวจสอบตามรอบที่กำหนด

Pressure-decay leak tester for isolator and RABS gloves. Wall-mounted touchscreen terminal with NFC card login and per-glove test records for scheduled integrity verification.', '[{"label": "วิธีทดสอบ / Test method", "value": "Pressure decay"}, {"label": "รูปแบบติดตั้ง / Installation", "value": "แบบติดผนัง — มีทั้งรุ่น Online และ Offline"}, {"label": "การเข้าใช้งาน / Access", "value": "ล็อกอินหน้าจอ + แตะบัตร NFC"}, {"label": "การบันทึกผล / Records", "value": "จัดเก็บผลรายถุงมือ ออกรายงานได้"}]'::jsonb, 330),
  ('neuronbc-glove-tester-multistation', 'ระบบทดสอบความสมบูรณ์ของถุงมือแบบหลายสเตชั่น', 'Multi-Station Glove Integrity Testing System', 'Neuronbc', 'Filter Integrity Tester, Packing Leak Tester, Glove Integrity Test, Bag Integrity Tester', 'device', '🧤', '/products/glove-tester-multistation.jpg', 'Networked glove testing stations', 'ระบบทดสอบการรั่วของถุงมือไอโซเลเตอร์แบบหลายสเตชั่น ต่อพ่วงเครื่องทดสอบติดผนังหลายตัวเข้ากับคอมพิวเตอร์กลางตัวเดียว เหมาะกับไลน์ผลิตที่มีไอโซเลเตอร์หรือ RABS หลายตู้ ผู้ปฏิบัติงานยืนยันตัวตนด้วยการแตะบัตรที่หน้าเครื่องแต่ละสเตชั่น ผลการทดสอบทุกสเตชั่นถูกรวบรวมไว้ที่ส่วนกลาง ทำให้ดูภาพรวมสถานะถุงมือทั้งโรงงานและออกรายงานรวมได้จากจุดเดียว

Multi-station isolator glove leak testing system — several wall-mounted testers networked to one central PC. Suited to lines running multiple isolators or RABS. Operators authenticate by NFC card at each station, and results from every station are collected centrally for a plant-wide view and consolidated reporting.', '[{"label": "วิธีทดสอบ / Test method", "value": "Pressure decay"}, {"label": "รูปแบบ / Configuration", "value": "เครื่องทดสอบติดผนังหลายสเตชั่น ต่อเข้าคอมพิวเตอร์กลาง"}, {"label": "การเข้าใช้งาน / Access", "value": "ล็อกอินหน้าจอ + แตะบัตร NFC ที่แต่ละสเตชั่น"}, {"label": "การบันทึกผล / Records", "value": "รวบรวมผลทุกสเตชั่นที่ส่วนกลาง ออกรายงานรวมได้"}, {"label": "แบรนด์ / Brand", "value": "Neuronbc"}]'::jsonb, 340),
  ('neuronbc-packing-leak-tester', 'เครื่องทดสอบการรั่วของบรรจุภัณฑ์', 'Packing Leak Tester', 'Neuronbc', 'Filter Integrity Tester, Packing Leak Tester, Glove Integrity Test, Bag Integrity Tester', 'device', '📦', '/products/packing-leak-tester.jpg', 'Package seal integrity testing', 'เครื่องทดสอบการรั่วซึมของบรรจุภัณฑ์แบบตั้งโต๊ะ ใช้ตรวจความสมบูรณ์ของรอยผนึกและซองบรรจุในงาน QC เช่น ซองอลูมิเนียม ถุงฟอยล์ และบรรจุภัณฑ์ปลอดเชื้อ ตัวเครื่องกะทัดรัดวางบนโต๊ะปฏิบัติการได้ ควบคุมผ่านหน้าจอสัมผัสสี ตั้งค่าพารามิเตอร์การทดสอบและเก็บผลไว้ในเครื่องเพื่อใช้เป็นหลักฐานการควบคุมคุณภาพ

Bench-top package leak tester for QC verification of seal and pouch integrity — foil pouches, sachets and sterile barrier packaging. Compact enough for a lab bench, with colour touchscreen control, configurable test parameters and stored results for QC records.', '[{"label": "รูปแบบ / Format", "value": "เครื่องตั้งโต๊ะ"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสสี ตั้งค่าพารามิเตอร์การทดสอบได้"}, {"label": "การบันทึกผล / Records", "value": "จัดเก็บผลทดสอบในเครื่อง"}, {"label": "แบรนด์ / Brand", "value": "Neuronbc"}]'::jsonb, 350),
  ('neuronbc-bag-integrity-tester', 'เครื่องทดสอบความสมบูรณ์ของถุงบรรจุแบบใช้ครั้งเดียว', 'Single-Use Bag Integrity Tester', 'Neuronbc', 'Filter Integrity Tester, Packing Leak Tester, Glove Integrity Test, Bag Integrity Tester', 'device', '🧪', '/products/bag-integrity-tester.jpg', 'Single-use bag leak testing', 'เครื่องทดสอบการรั่วของถุงบรรจุแบบใช้ครั้งเดียว (single-use bag) สำหรับตรวจความสมบูรณ์ของถุงก่อนนำไปบรรจุของเหลวในกระบวนการผลิตชีววัตถุ ช่วยลดความเสี่ยงที่ถุงจะรั่วระหว่างใช้งานและทำให้เสียแบตช์ทั้งชุด ตัวเครื่องสเตนเลสพร้อมหูหิ้ว เคลื่อนย้ายไปทดสอบหน้างานได้ ควบคุมผ่านหน้าจอสัมผัส พร้อมระบบล็อกอินและบันทึกผลรายถุง

Leak tester for single-use bioprocess bags, verifying bag integrity before liquid is filled — reducing the risk of a leak mid-process and the loss of an entire batch. Portable stainless housing with a carry handle for point-of-use testing, touchscreen control with user login and per-bag result records.', '[{"label": "ใช้กับ / Application", "value": "ถุงบรรจุแบบใช้ครั้งเดียวในกระบวนการผลิตชีววัตถุ"}, {"label": "รูปแบบ / Format", "value": "ตัวเครื่องสเตนเลสพร้อมหูหิ้ว เคลื่อนย้ายได้"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัส พร้อมระบบล็อกอินผู้ใช้"}, {"label": "การบันทึกผล / Records", "value": "จัดเก็บผลทดสอบรายถุง"}, {"label": "แบรนด์ / Brand", "value": "Neuronbc"}]'::jsonb, 360),
  ('belimed-lst-v-lab-sterilizer', 'หม้อนึ่งฆ่าเชื้อสำหรับห้องปฏิบัติการ LST-V (ประตูเลื่อนแนวตั้ง)', 'LST-V Laboratory Steam Sterilizer — Vertical Sliding Doors', 'SteelcoBelimed', 'Laboratory Autoclave', 'device', '♨️', '/products/lst-v-lab-autoclave.jpg', 'The most compact in its class', 'หม้อนึ่งฆ่าเชื้อด้วยไอน้ำสำหรับห้องปฏิบัติการวิจัย มหาวิทยาลัย และห้องปฏิบัติการชีวนิรภัย ประตูเลื่อนแนวตั้ง เลือกได้ทั้งประตูเดี่ยวและประตูคู่ จุดเด่นคือใช้พื้นที่ติดตั้งน้อยมากเมื่อเทียบกับความจุ (ห้องขนาด 6-6-6 ใช้พื้นที่เพียง 1 ตร.ม. สูง 2 ม.) ระดับความสูงในการโหลดที่ 78 ซม. ช่วยให้ทำงานได้สะดวก ควบคุมผ่านหน้าจอสัมผัสพร้อมระบบสิทธิ์ผู้ใช้หลายระดับ บันทึกอุณหภูมิและความดันตลอดรอบ พร้อมเครื่องพิมพ์ในตัว รองรับการทำ validation ได้เต็มรูปแบบ ถอดแผงหน้าเข้าถึงอุปกรณ์ทุกชิ้นได้จากด้านหน้า ผลิตในสวิตเซอร์แลนด์

Laboratory steam sterilizer for research institutes, universities and biocontainment facilities. Vertical sliding doors, available single or double. Best-in-class footprint — a 6-6-6 chamber needs only 1 m² and 2 m of height — with an ergonomic 78 cm loading height. Touchscreen control with password-protected authorization levels, continuous temperature and pressure recording and an integrated printer. Fully validatable, with all components accessible from the front. Swiss made.', '[{"label": "ปริมาตรห้องฆ่าเชื้อ / Chamber volume", "value": "300 – 870 ลิตร"}, {"label": "ประตู / Doors", "value": "เลื่อนแนวตั้ง — ประตูเดี่ยวหรือประตูคู่"}, {"label": "ความสูงในการโหลด / Loading height", "value": "78 ซม."}, {"label": "พื้นที่ติดตั้ง / Footprint", "value": "เพียง 1 ตร.ม. สูง 2 ม. (ห้องขนาด 6-6-6)"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัส พร้อมสิทธิ์ผู้ใช้หลายระดับและเครื่องพิมพ์ในตัว"}, {"label": "การใช้งาน / Applications", "value": "ของแข็ง/วัสดุพรุน ของเหลว วุ้นเลี้ยงเชื้อ เครื่องแก้ว และการทำลายเชื้อของเสียห้องแล็บ"}, {"label": "ตัวเลือกเพิ่มเติม / Options", "value": "เครื่องกำเนิดไอน้ำในตัว, โปรแกรมกำจัดของเสีย, ระบบบันทึกรอบ ICS 8535"}, {"label": "แหล่งผลิต / Origin", "value": "Swiss Made"}]'::jsonb, 370),
  ('steelco-undercounter-lab-washer', 'เครื่องล้างเครื่องแก้วแบบติดตั้งใต้เคาน์เตอร์', 'Undercounter Laboratory Glassware Washer', 'SteelcoBelimed', 'Undercounter Laboratory Washer', 'device', '🧼', '/products/steelco-undercounter-lab-washer.jpg', 'Bench-integrated glassware washing', 'เครื่องล้างเครื่องแก้วสำหรับห้องปฏิบัติการ ออกแบบให้มีความสูงพอดีกับการติดตั้งใต้เคาน์เตอร์ห้องแล็บ จึงใช้พื้นที่ห้องได้คุ้มค่าโดยไม่ต้องกันพื้นที่วางเครื่องแยก หรือจะติดตั้งแบบตั้งพื้นบนฐานรองที่มีมาให้ก็ได้ ภายในรองรับแร็คหลายชั้นพร้อมหัวฉีดสอดสำหรับล้างเครื่องแก้วคอแคบ เช่น ขวดวัดปริมาตร ขวดรูปชมพู่ และหลอดทดลอง แผงควบคุมพาดตลอดความกว้างด้านบนประตู แสดงโปรแกรมที่เลือกและเวลาที่เหลือของรอบการล้าง ประตูเลือกได้สองแบบ คือบานกระจกสีน้ำเงินพร้อมช่องมองสำหรับดูการล้างขณะทำงาน และบานสเตนเลสทึบสำหรับห้องที่ต้องการผิวสเตนเลสทั้งชุด

Laboratory glassware washer sized to fit under a standard lab bench, saving floor space, or to stand freely on the supplied plinth. Multi-level racks with injection spindles clean narrow-neck labware such as volumetric flasks, conical flasks and test tubes. A full-width control panel above the door shows the selected programme and time remaining. The door is available either in blue glass with a viewing window to follow the wash, or in solid stainless steel for rooms specified in full stainless.', '[{"label": "รูปแบบ / Format", "value": "ติดตั้งใต้เคาน์เตอร์ หรือแบบตั้งพื้นบนฐานรอง"}, {"label": "ประตู / Door", "value": "เลือกได้ระหว่างบานกระจกพร้อมช่องมอง และบานสเตนเลสทึบ"}, {"label": "ระบบล้าง / Washing", "value": "แร็คหลายชั้น พร้อมหัวฉีดสอดสำหรับเครื่องแก้วคอแคบ"}, {"label": "การควบคุม / Control", "value": "แผงควบคุมด้านบนประตู แสดงโปรแกรมและเวลาที่เหลือ"}, {"label": "การใช้งาน / Application", "value": "ล้างขวดวัดปริมาตร ขวดรูปชมพู่ หลอดทดลอง และเครื่องแก้วห้องปฏิบัติการ"}, {"label": "แบรนด์ / Brand", "value": "SteelcoBelimed"}]'::jsonb, 380),
  ('bioengineering-taberis-xpert-a', 'ระบบเลี้ยงเชื้อ/ถังปฏิกรณ์ชีวภาพตั้งโต๊ะ Taberis Xpert A', 'Taberis Xpert A Bench-Top Fermenter / Bioreactor', 'Bioengineering', 'Laboratory / Bench Top Fermentor / Bioreactor', 'device', '🧫', '/products/taberis-xpert-a.jpg', 'Bench-top fermenter & bioreactor system', 'ระบบเลี้ยงเชื้อและถังปฏิกรณ์ชีวภาพขนาดตั้งโต๊ะ ในตระกูล Taberis ประกอบด้วยชุดควบคุมกลางพร้อมหน้าจอสัมผัสขนาดใหญ่ และถังปฏิกรณ์แก้วที่ผ่านการนึ่งฆ่าเชื้อได้ พร้อมฝาสเตนเลสหลายพอร์ตสำหรับติดตั้งหัววัดและสายป้อนสารต่าง ๆ ชุดควบคุมเดียวเดินได้หลายถังขนานกัน เหมาะกับงานพัฒนากระบวนการ งานวิจัยจุลชีววิทยา และการทำ scale-down จากสายการผลิต หน้าจอแสดงค่ากระบวนการและกราฟแนวโน้มแบบเรียลไทม์ พร้อมบันทึกเหตุการณ์ของแต่ละแบตช์

Bench-top fermenter and bioreactor system from the Taberis family. A central control tower with a large touchscreen drives autoclavable glass vessels fitted with multi-port stainless head plates for probes and feed lines, and a single controller can run several vessels in parallel. Suited to process development, microbiology research and scale-down work, with live process values, trend charts and per-batch event logging on screen.', '[{"label": "ตระกูลสินค้า / Product family", "value": "Taberis (Xpert A / Prime I / Parasmart)"}, {"label": "รูปแบบ / Format", "value": "ชุดควบคุมตั้งโต๊ะ พร้อมถังปฏิกรณ์แก้วนึ่งฆ่าเชื้อได้"}, {"label": "การเดินหลายถัง / Multi-vessel", "value": "ชุดควบคุมเดียวรองรับหลายถังขนานกัน (ภาพแสดง 2 ถัง)"}, {"label": "การควบคุม / Control", "value": "หน้าจอสัมผัสขนาดใหญ่ แสดงค่ากระบวนการ กราฟแนวโน้ม และบันทึกเหตุการณ์รายแบตช์"}, {"label": "ฝาถัง / Head plate", "value": "สเตนเลสหลายพอร์ต สำหรับหัววัดและสายป้อนสาร"}, {"label": "แบรนด์ / Brand", "value": "Bioengineering"}]'::jsonb, 390),
  ('ami-polymer-lab-silicone-tubing', 'ท่อซิลิโคนสำหรับห้องปฏิบัติการ', 'Silicone Tubing for Laboratory', 'Ami Polymer', 'Silicone Tubing for Laboratory', 'tube', '🧬', '/products/ami-polymer-lab-silicone-tubing.jpg', 'Flexible tubing for bench-scale work', 'ท่อซิลิโคนเนื้อใสสำหรับงานห้องปฏิบัติการ มีหลายขนาดเส้นผ่านศูนย์กลางให้เลือกตามอัตราการไหลและอุปกรณ์ที่ต่อใช้งาน ใช้ต่อระหว่างเครื่องแก้ว เครื่องมือวิเคราะห์ และชุดกรอง รวมถึงงานปั๊มรีดท่อ (peristaltic pump) และการถ่ายเทของเหลวปริมาณน้อยในงานทดลอง เนื้อท่อยืดหยุ่นสูงและคืนตัวดี ดัดโค้งได้โดยไม่หักพับ ผนังใสมองเห็นของเหลวและฟองอากาศภายในได้ตลอดแนว ผิวภายในเรียบช่วยลดการเกาะของอนุภาค ทนการนึ่งฆ่าเชื้อด้วยไอน้ำจึงนำกลับมาใช้ซ้ำได้ตามรอบที่กำหนด

Clear silicone tubing for laboratory work, available in a range of bore sizes to match flow rate and the equipment being connected. Used between glassware, instruments and filter assemblies, for peristaltic pumping and for small-volume liquid transfer on the bench. Highly flexible with good recovery, it bends without kinking; the clear wall keeps liquid and air bubbles visible along its length, and the smooth bore limits particle adhesion. Steam sterilisable, so it can be reused on a defined cycle.', '[{"label": "วัสดุ / Material", "value": "ซิลิโคน เนื้อใส"}, {"label": "ขนาด / Sizes", "value": "มีหลายขนาดเส้นผ่านศูนย์กลาง (ภาพแสดง 3 ขนาด)"}, {"label": "การใช้งาน / Application", "value": "ต่อเครื่องแก้วและเครื่องมือ, ปั๊มรีดท่อ และการถ่ายเทของเหลวในห้องแล็บ"}, {"label": "คุณสมบัติ / Properties", "value": "ยืดหยุ่นสูง คืนตัวดี ดัดโค้งไม่หักพับ ผิวในเรียบ"}, {"label": "การฆ่าเชื้อ / Sterilisation", "value": "นึ่งฆ่าเชื้อด้วยไอน้ำได้"}, {"label": "แบรนด์ / Brand", "value": "Ami Polymer"}]'::jsonb, 400),
  ('filtrox-activasorb-test-kit', 'ชุดทดสอบการกรอง ACTIVASORB® สำหรับงานขยายกำลังผลิต', 'ACTIVASORB® Test Kit', 'Filtrox', 'Filtration Trials Test Kit for Scale-up', 'kit', '🧰', '/products/filtrox-activasorb-test-kit.jpg', 'Bench trials that scale to production', 'ชุดทดสอบการกรองระดับห้องปฏิบัติการ สำหรับคัดเลือกเกรดแผ่นกรองเชิงลึกที่เหมาะกับของเหลวแต่ละชนิดก่อนสั่งซื้อจริง ภายในกล่องบรรจุแผ่นกรองตัวอย่างครบทั้ง 6 เกรดของซีรีส์ ACTIVASORB® ได้แก่ PXS, PX, CA, BM, BMC และ LWT พร้อมชุดยึดแผ่นกรอง สายซิลิโคน และอุปกรณ์ประกอบการทดลอง จึงเริ่มทดสอบได้ทันทีโดยไม่ต้องจัดหาอุปกรณ์เพิ่ม ฝากล่องพิมพ์คำแนะนำการใช้งาน 4 ภาษา พร้อมผังขั้นตอนตั้งแต่การตั้งค่าการทดลอง การคำนวณเพื่อขยายขนาด (scale-up) ไปจนถึงการนำผลไปใช้กับชุดกรองระดับการผลิต ทำให้เทียบผลจากการทดลองบนโต๊ะไปเป็นพื้นที่กรองที่ต้องใช้จริงได้โดยตรง กล่องออกแบบเป็นหูหิ้ว พกพาไปทดสอบที่หน้างานลูกค้าได้

Bench-scale filtration trial kit for selecting the right depth filter grade for a given liquid before committing to a purchase. The case holds sample sheets of all six ACTIVASORB® grades — PXS, PX, CA, BM, BMC and LWT — together with the sheet holder, silicone tubing and trial accessories, so testing can start without sourcing anything else. The lid carries four-language instructions and a workflow diagram covering trial setup, the scale-up calculation and implementation on production-scale housings, so bench results translate directly into the filter area required. The case has a carry handle for trials at the customer''s site.', '[{"label": "รูปแบบ / Format", "value": "ชุดทดสอบระดับห้องปฏิบัติการ ในกล่องพร้อมหูหิ้ว"}, {"label": "เกรดในชุด / Grades included", "value": "ACTIVASORB® PXS, PX, CA, BM, BMC และ LWT"}, {"label": "อุปกรณ์ในชุด / Contents", "value": "แผ่นกรองตัวอย่างแต่ละเกรด, ชุดยึดแผ่นกรอง, สายซิลิโคน และอุปกรณ์ประกอบ"}, {"label": "คู่มือ / Instructions", "value": "คำแนะนำ 4 ภาษา พร้อมผังขั้นตอนการทดลองและการคำนวณ scale-up"}, {"label": "วัตถุประสงค์ / Purpose", "value": "คัดเลือกเกรดแผ่นกรองและคำนวณพื้นที่กรองสำหรับระดับการผลิต"}, {"label": "แบรนด์ / Brand", "value": "Filtrox"}]'::jsonb, 410),
  ('lepure-capsule-disc-filters', 'แคปซูลกรอง แผ่นกรองดิสก์ และตัวกรองปลายเข็มฉีดยา', 'Filter Capsules, Disc Filters & Syringe Filters', 'Le Pure', 'Vacuum Filter Unit / Air Filter Disc / Capsule', 'kit', '💧', '/products/lepure-capsule-disc-filters.jpg', 'Lab-scale capsules and disc filters', 'กลุ่มตัวกรองแบบใช้ครั้งเดียวสำหรับงานห้องปฏิบัติการและงานนำร่อง ตั้งแต่แคปซูลกรองขนาดเล็กสำหรับกรองตัวอย่างและระบายอากาศ (venting) แคปซูลขนาดกลางสำหรับงานทดลองปริมาณมากขึ้น ไปจนถึงแผ่นกรองแบบดิสก์และตัวกรองปลายเข็มฉีดยาสำหรับเตรียมตัวอย่างวิเคราะห์ ตัวกรองปลายเข็มฉีดยาใช้สีของวงแหวนแยกขนาดรูกรองและชนิดเมมเบรนเพื่อลดการหยิบผิด หัวต่อมีทั้งแบบสวมสายและแบบหน้าแปลนสุขอนามัย ทุกตัวใช้เมมเบรนชนิดเดียวกับสินค้าระดับผลิต จึงใช้ทดลองเพื่อขยายกำลังการผลิตต่อได้

Single-use filters for laboratory and pilot work — from small capsules for sample filtration and venting, through mid-size capsules for larger trials, to disc and syringe filters for analytical sample prep. Syringe filters are colour-coded by pore size and membrane to prevent mix-ups; connections include hose barb and sanitary flange. All share the membranes used in the production-scale range, so trial results scale up directly.', '[{"label": "ผลิตภัณฑ์ในกลุ่ม / Range", "value": "แคปซูลกรองขนาดเล็ก–กลาง, แผ่นกรองดิสก์ และตัวกรองปลายเข็มฉีดยา"}, {"label": "การใช้งาน / Application", "value": "กรองตัวอย่าง เตรียมตัวอย่างวิเคราะห์ กรองอากาศ และระบายอากาศ (venting)"}, {"label": "การเชื่อมต่อ / Connections", "value": "หัวต่อแบบสวมสาย และแบบหน้าแปลนสุขอนามัย"}, {"label": "การแยกประเภท / Colour coding", "value": "ตัวกรองปลายเข็มฉีดยาแยกสีตามขนาดรูกรองและชนิดเมมเบรน"}, {"label": "การขยายกำลังผลิต / Scale-up", "value": "ใช้เมมเบรนชนิดเดียวกับสินค้าระดับผลิต"}, {"label": "แบรนด์ / Brand", "value": "Le Pure"}]'::jsonb, 420)
on conflict (id) do update set
  name        = excluded.name,
  name_en     = excluded.name_en,
  brand       = excluded.brand,
  category    = excluded.category,
  tone        = excluded.tone,
  icon        = excluded.icon,
  image       = excluded.image,
  tagline     = excluded.tagline,
  description = excluded.description,
  specs       = excluded.specs,
  sort_order  = excluded.sort_order;
